# Generated by Django 2.1 on 2018-09-15 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deckbuilder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('answers', models.ManyToManyField(related_name='_deckcomment_answers_+', to='deckbuilder_app.DeckComment')),
            ],
        ),
        migrations.CreateModel(
            name='GalaxyDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GalaxyMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[(0, 'Normal'), (1, 'Nightmare'), (2, 'Hell')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='art',
            field=models.ImageField(blank=True, null=True, upload_to='cards'),
        ),
        migrations.AlterField(
            model_name='card',
            name='race',
            field=models.IntegerField(choices=[(0, 'Quadruple Radiance Empire'), (1, 'Roughrock Weald'), (2, 'Inferno'), (3, "Deus of Winter's Apostle"), (4, 'Zen Valley'), (5, 'Recluse'), (6, 'Paradise Harbor')], default='Quadruple Radiance Empire'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/default/profile_image.jpg', upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='galaxymap',
            name='cards',
            field=models.ManyToManyField(to='deckbuilder_app.Card'),
        ),
        migrations.AddField(
            model_name='galaxymap',
            name='related_decks',
            field=models.ManyToManyField(through='deckbuilder_app.GalaxyDeck', to='deckbuilder_app.Deck'),
        ),
        migrations.AddField(
            model_name='galaxydeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deckbuilder_app.Deck'),
        ),
        migrations.AddField(
            model_name='galaxydeck',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deckbuilder_app.GalaxyMap'),
        ),
        migrations.AddField(
            model_name='deckcomment',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deckbuilder_app.Deck'),
        ),
        migrations.AddField(
            model_name='deckcomment',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deckbuilder_app.DeckComment'),
        ),
        migrations.AddField(
            model_name='deckcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deck',
            name='tags',
            field=models.ManyToManyField(to='deckbuilder_app.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='galaxymap',
            unique_together={('name', 'difficulty')},
        ),
    ]
