# Generated by Django 2.1 on 2018-09-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckbuilder_app', '0002_deck_properties_comments_galaxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galaxymap',
            name='campaign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='galaxymap',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galaxymap',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='galaxymap',
            name='difficulty',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='galaxymap',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='galaxymap',
            unique_together=set(),
        ),
    ]
